### ISSUE TITLE
Pet-clinic shall open in a window with navigation buttons

### ISSUE THREAD

**Issue by mboehm3** [dxc-technology/online-devops-dojo#60]
**Is your feature request related to a problem? Please describe.**
In the continuous-integration module in step 8 is a link to the pet-clinic app. The app opens in a tab in the katacoda window which has no navigation buttons. Navigating back from a page in the app is only possible through the context menu.

**Describe the solution you'd like**
If the pet-clinic app would open in a separate browser window, it would make the navigation in the app easier.

**Comment by pberthonneau** [comment]
Normally you can click the icon in Katacoda tab
![image](https://user-images.githubusercontent.com/52540205/84799164-28d6b300-affc-11ea-9fd6-acdd1665de77.png)
if you want a genuine browser tab.
The problem is with too many tabs, students get lost.
We had to make an exception with Jenkins tab as a workaround for a Chrome sameSite cookie issue.
