### ISSUE TITLE
Need assistance with module welcome

### ISSUE THREAD

**Issue by jontankersley** [dxc-technology/online-devops-dojo#89]
**Unable to proceed with Shift Left**
I started the dojo yesterday and didn't finish.  The Shift Left didn't allow me to continue.

**To Reproduce**
Hard to say... start at 3PM and not get done and try again in the morning.

**Expected behavior**
progressing through Shift Left with Security.

**Screenshots**
![image](https://user-images.githubusercontent.com/62358859/105872314-e2006100-5fbf-11eb-8af3-892329b416ae.png)

**Additional context**
The first failure was with the Jenkins step. My output didn't match the example around step 5 or 6.
I've tried restarting with the Welcome and it isn't working.
Looking at my github, the master is basically empty, but the branches are not.  The deps-check is the newest branch as part of Shift Left.

![image](https://user-images.githubusercontent.com/62358859/105872521-22f87580-5fc0-11eb-9fba-70ca99275326.png)

I may need to do a cold restart?

**Comment by ojacques** [comment]
@jontankersley - interesting.
Indeed, the master branch is essentially empty while other branches are fine. Because there is no git history either on master, I suspect that a "force push" got you in that state. 

The easiest should be to follow these steps:
* Delete your pet-clinic repository (do not worry, the Dojo will create it again for you) or rename it
* Go through the Welcome module again
* Start the "shift left on security" module

And let us know how it goes!

**Comment by tom-halpin** [comment]
@jontankersley note you have included a token in the screen shot above, strongly recommend you delete and recreate the token if you haven't already.

**Comment by jontankersley** [comment]
Sigh….

Even issue logging…provide a screenshot... Not sure people will remember that, I know I wouldn’t have.
